language: node_js
node_js:
    - 6
install:
|
    npm install -g npm@latest
    npm --version
    npm install --registry http://registry.npmjs.org
after_success:
- npm run coveralls
branches:
  only:
    - gh-pages